version: "3"

services:
  nginx:
    image: panteparak/iot-demo-ui
    restart: unless-stopped
    ports:
      - 8088:80
    depends_on:
      - backend

  backend:
    image: panteparak/iot-demo-express
    restart: unless-stopped
    